var a = 10;
var fname = "taj hotel";
var result = true;
//a="tavi";
var info = "welcome";
info = false;
info = 200;
var b = 200;
var lname = "Ravi kumar";
var result2 = false;
var id;
var fullname;
var result3;
id = 300;
fullname = "ajay";
result3 = true;
console.log(a);
console.log(fname);
console.log(result);
